### ISSUE TITLE
HIP_PLATFORM=nvcc, cmake error 

### ISSUE THREAD

**Issue by yaomingamd** [ROCmSoftwarePlatform/rocPRIM#125]
Try to compare performance for MI50 and NVIDIA V100, for AMD system, build and test are successfull, but for NVIDIA system set HIP_PLATFORM=nvcc, CMAKE error
CXX=hipcc cmake -DBUILD_BENCHMARK=ON ..
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /opt/rocm/bin/hipcc
-- Check for working CXX compiler: /opt/rocm/bin/hipcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Warning (dev) at CMakeLists.txt:44 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found HIP: /opt/rocm (found suitable version "3.0.19493-36529b16", minimum required is "1.5.18263")
CMake Error at cmake/VerifyCompiler.cmake:61 (message):
  HIP_PLATFORM must be 'hcc' (AMD ROCm platform)
Call Stack (most recent call first):
  CMakeLists.txt:47 (include)

-- Configuring incomplete, errors occurred!
See also "/home/alice/test/rocPRIM/build/CMakeFiles/CMakeOutput.log".
[alice@prj47-rack-96 build]$ CXX=hcc cmake -DBUILD_BENCHMARK=ON ..
CMake Warning (dev) at CMakeLists.txt:44 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/VerifyCompiler.cmake:61 (message):
  HIP_PLATFORM must be 'hcc' (AMD ROCm platform)
Call Stack (most recent call first):
  CMakeLists.txt:47 (include)

-- Configuring incomplete, errors occurred!
See also "/home/alice/test/rocPRIM/build/CMakeFiles/CMakeOutput.log".
[alice@prj47-rack-96 build]$ CXX=hcc cmake -DBUILD_BENCHMARK=ON ..
CMake Warning (dev) at CMakeLists.txt:44 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/VerifyCompiler.cmake:61 (message):
  HIP_PLATFORM must be 'hcc' (AMD ROCm platform)
Call Stack (most recent call first):
  CMakeLists.txt:47 (include)

-- Configuring incomplete, errors occurred!
See also "/home/alice/test/rocPRIM/build/CMakeFiles/CMakeOutput.log".
[alice@prj47-rack-96 build]$ CXX=hipcc cmake -DBUILD_BENCHMARK=ON ..
CMake Warning (dev) at CMakeLists.txt:44 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/VerifyCompiler.cmake:61 (message):
  HIP_PLATFORM must be 'hcc' (AMD ROCm platform)
Call Stack (most recent call first):
  CMakeLists.txt:47 (include)

-- Configuring incomplete, errors occurred!
See also "/home/alice/test/rocPRIM/build/CMakeFiles/CMakeOutput.log".

**Comment by saadrahim** [comment]
rocPRIM does not build with nvcc
