### ISSUE TITLE
memory access fault when linking dynamic lib that uses hipcub

### ISSUE THREAD

**Issue by ntrost57** [ROCmSoftwarePlatform/rocPRIM#13]
I am running into a memory access fault when linking to a dynamic library that uses hipcub if I use hipcub also in the main program (that links to the package that uses hipcub).
Please see the following minimal example [hipcub_test.tar.gz](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/2144332/hipcub_test.tar.gz)

Edit: This does not happen when using rocprim or cub instead of hipcub.

**Comment by jszuppe** [comment]
I'll look into it.

**Comment by jszuppe** [comment]
We identified the problem: for some reasons in said configuration (linking to a dynamic library that uses hipcub if I use hipcub also in the main program) every kernel is **run twice** by HIP framework. Some kernels are resistant to that, some are not (access errors). We are not sure why it happens only for hipCUB.

Right now we are thinking that probably in [here](https://github.com/ROCm-Developer-Tools/HIP/blob/836627279fd5bd995910c471882743accef5ec58/src/functional_grid_launch.inl#L126) should be a break after `hipModuleLaunchKernel()`.

**Comment by jszuppe** [comment]
Should be fixed by https://github.com/ROCm-Developer-Tools/HIP/pull/575. I don't know which ROCm release will include that.
