### ISSUE TITLE
Unable to build rocPRIM

### ISSUE THREAD

**Issue by gowthamcr** [ROCmSoftwarePlatform/rocPRIM#14]
I am still observing the issue #10 
https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/10,

Even i tried with the fix__half_tests_on_new_hip branch, even with this branch also i am observing the issue.
[rocPRIM_MasterBranch_issue.log](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/2158562/rocPRIM_MasterBranch_issue.log)

I have attached the complete log for both master and fix__half_tests_on_new_hip branch 
[fix_half_log.txt](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/2158602/fix_half_log.txt)

**Comment by jszuppe** [comment]
Environment?

**Comment by ex-rzr** [comment]
@gowthamcr, I have pushed the fix: https://github.com/ROCmSoftwarePlatform/rocPRIM/tree/fix_half_tests_on_new_hip

Please let us know if it work for you.

**Comment by gowthamcr** [comment]
@ex-rzr Tried with the fix_half_tests_on_new_hip branch, its working fine now
