### ISSUE TITLE
temporary buffer allocation

### ISSUE THREAD

**Issue by ntrost57** [ROCmSoftwarePlatform/rocPRIM#16]
I am running into a gpu memory access fault when I do not explicitly allocate the temporary buffer that is required in rocprim for each function call.

What works:
```
hipcub::DeviceRadixSort::SortPairs(nullptr, size, ...);
hipMalloc(&buffer, size);
hipcub::DeviceRadixSort::SortPairs(buffer, size, ...);
hipFree(buffer);

hipcub::DeviceRunLengthEncode::Encode(nullptr, size, ...);
hipMalloc(&buffer, size);
hipcub::DeviceRunLengthEncode::Encode(buffer, size, ...);
hipFree(buffer);

hipcub::DeviceScan::ExclusiveSum(nullptr, size, ...);
hipMalloc(&buffer, size);
hipcub::DeviceScan::ExclusiveSum(buffer, size, ...);
hipFree(buffer);

hipcub::DeviceSegmentedRadixSort::SortPairs(nullptr, size, ...);
hipMalloc(&buffer, size);
hipcub::DeviceSegmentedRadixSort::SortPairs(buffer, size, ...);
hipFree(buffer);
```

What does not work:
```
size_t total_size = 0;
hipcub::DeviceRadixSort::SortPairs(nullptr, size, ...);
total_size = std::max(total_size, size);
hipcub::DeviceRunLengthEncode::Encode(nullptr, size, ...);
total_size = std::max(total_size, size);
hipcub::DeviceScan::ExclusiveSum(nullptr, size, ...);
total_size = std::max(total_size, size);
hipcub::DeviceSegmentedRadixSort::SortPairs(nullptr, size, ...);
total_size = std::max(total_size, size);

total_size += sizeof(int) * some_other_size * 3;

void* buffer;
hipMalloc(&buffer, total_size);

// do some other stuff...

char* ptr = reinterpret_cast<char*>(buffer);

int* work1 = reinterpret_cast<int*>(ptr);
ptr += sizeof(int) * some_other_size;

int* work2 = reinterpret_cast<int*>(ptr);
ptr += sizeof(int) * some_other_size;

int* work3 = reinterpret_cast<int*>(ptr);
ptr += sizeof(int) * some_other_size;

void* hipcub_buffer = reinterpret_cast<void*>(ptr);

hipcub::DeviceRadixSort::SortPairs(hipcub_buffer, size, ...);
hipcub::DeviceRunLengthEncode::Encode(hipcub_buffer, size, ...);
hipcub::DeviceScan::ExclusiveSum(hipcub_buffer, size, ...);
hipcub::DeviceSegmentedRadixSort::SortPairs(hipcub_buffer, size, ...);
```

**Comment by jszuppe** [comment]
`total_size += sizeof(int) * some_other_size * 3;` - this might be the problem. Alignment might be wrong. `hipcub_buffer` should have the same alignment as if it was allocated using `hipMalloc`.

**Comment by ntrost57** [comment]
Then it should work, if the ```hipcub_buffer``` is the first chunk of buffer data in the row, right?

**Comment by jszuppe** [comment]
I guess. I don't see any other problem right now, but only looked at your code. If you are allocating multiple buffers with one `hipMalloc` I'd recommend aligning every buffer to 256 bytes. It's not much and it helps.

**Comment by ntrost57** [comment]
Works, thanks!
Btw: Buffer size returned by rocprim is not a multiple of 256.
I think I remember that for some nvidia cards pointer alignment is not always 256, do you happen to have any information on that or am I wrong.

**Comment by jszuppe** [comment]
> Btw: Buffer size returned by rocprim is not a multiple of 256.

That's true. Temporary buffer size does not have to be a multiple of 256. However, its pointer may need to be aligned to 256 bytes.

> I think I remember that for some nvidia cards pointer alignment is not always 256, do you happen to have any information on that or am I wrong.

From NVIDIA docs: "Any address of a variable residing in global memory or returned by one of the memory allocation routines from the driver or runtime API is always aligned to at least 256 bytes." It might be more on newer GPUs, but 256 bytes is good enough for everything to work correctly.

**Comment by ntrost57** [comment]
Great, thanks a lot!
