### ISSUE TITLE
When are we going to push changes from fix_half_tests_on_new_hip branch to master

### ISSUE THREAD

**Issue by rkothako** [ROCmSoftwarePlatform/rocPRIM#17]

**Comment by ex-rzr** [comment]
Currently these changes are merged into `develop` branch (which also contains some changes for the latest HIP versions).

**Comment by rkothako** [comment]
Thanks. Please let know once the changes are in master branch.
We are taking code from master only, mostly, hence this request.

**Comment by ncrkblacksmith** [comment]
The requested changes have been pushed to the master branch.

**Comment by ncrkblacksmith** [comment]
Can we remove the `fix_half_tests_on_new_hip` branch?

**Comment by rkothako** [comment]
Thanks for pushing to master.
I will validate in few mins and update you please....

**Comment by rkothako** [comment]
@ncrkblacksmith 
I have observed that test count decreased from around 90 to 55, is it expected?

**Comment by jszuppe** [comment]
@rkothako That's for reporting that. We will fix that, it's unexpected change caused by other PRs merge for compatibility with hip-clang (hcc tests were disabled). We will update `master` and `develop` today to address that.

**Comment by jszuppe** [comment]
@rkothako It's fixed. CI didn't complain there was less tests, so we missed that problem. Thanks again!

**Comment by rkothako** [comment]
Wonderful. all tests are PASSING on VEGA10 and VEGA20.

**Comment by jszuppe** [comment]
I'll remove `fix_half_tests_on_new_hip` later today.
