### ISSUE TITLE
Block_reduce fails to distribute correct answer to all lanes when hipBlockDim > 64

### ISSUE THREAD

**Issue by dragontamer** [ROCmSoftwarePlatform/rocPRIM#179]
**Describe the bug**

Block_reduce seems to output incorrect values when hipBlockDim > 64 on my Vega64. There seems to be a bug in distributing the output to other warps. The attached example.cpp provides an easy demonstration of the bug.

The #define for NUM_THREADS provides an easy set of tests for the values 64, 128, 192, and 256. NUM_THREADS == 64 outputs all correct answers. However, 128 only produces the correct answer in two threads (Thread0 and Thread1). 192 produces the correct answer in one lanes (Only thread0), while 256 produces the correct answer in only four lanes.

The block_reduce code is clearly missing the "broadcast" step in some cases, where Thread0 broadcasts the value back to all 256 threads.

**To Reproduce**

[example.cpp.txt](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/5072473/example.cpp.txt)

Compile the attached "example.cpp" file with `hipcc example.cpp -I/opt/rocm/rocprim/include/`. Play with the #define NUM_THREADS value as you see fit.

**Expected behavior**
In the case of 192-threads, I expect 18336 (0+1+2+3+4...+191) to be the output for all 192-lanes.

**Log-files**

The following output is from a NUM_THREADS of 192. The value of 18336 in thread0 is correct, but has failed to be distributed to other lanes.

> 18336
16320
10208
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
2016
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
6112
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208
10208

**Comment by doctorcolinsmith** [comment]
@dragontamer Thanks for including the sample code.  A developer is now reviewing this report.

**Comment by ncrkblacksmith** [comment]
@dragontamer

I believe your assumptions about how a block reduction algorithm works within our library (or even CUB) are wrong.

A block reduction algortihm holds the result only on the first thread of the block. This is in fact how it is implemented.

The reason that you think this is incorrect for block sizes of larger than 64 is simply because the warp size is 64 and with block sizes of less than 64 only one warp reduction is being done.

But when the block size is bigger than a warp. The block reduction algorithm only stores the result only in the first thread(lane_id = 0 warp_id = 0). Keep in mind that block reduction is different than warp reduction.

So if you require propagation of the results to all threads you have to do them manually. For example:
```
__global__ void helloworld(int64_t* buffer){

    // We need a shared variable to store the result of the reduction for propagation in all threads
    __shared__ int64_t final_result;

    int64_t reduction;
    typedef rocprim::block_reduce<int64_t, NUM_THREADS> MyReduce;
    MyReduce().reduce(hipThreadIdx_x, reduction); 

    // The first thread will update the final_result shared variable so that all threads have access to it
    if(hipThreadIdx_x == 0)
    {
        final_result = reduction;
    }
    sync_threads();
    
    // All threads will now fill the buffer with the final_result 
    buffer[hipThreadIdx_x] = final_result; 
}
```

**Comment by dragontamer** [comment]
@ncrkblacksmith : If that is the intended use of block_reduction, then it should be documented somewhere.

None of the Doxygen comments indicate that ouput is only valid in lane0. In fact, the documentation here suggests that the answer is distributed to all 256 lanes: https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/develop/rocprim/include/rocprim/block/block_reduce.hpp#L222

**Comment by doctorcolinsmith** [comment]
We will get the documentation updated in a future release.
