### ISSUE TITLE
TF unit test fails due to a crash in rocprim

### ISSUE THREAD

**Issue by deven-amd** [ROCmSoftwarePlatform/rocPRIM#18]
I have attached a testcase which is a truncated version of a TF unit testcase.
(rename file to drop the .txt extension, that was added so I can attach the file to this issue)

Run it as shown below (within a container with ROCm tensorflow 1.8)

"python3 histogram_ops_test.py"   

and you should see the crash.  The crash corresponds to this call in rocprim

https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/master/rocprim/include/rocprim/device/device_histogram_hip.hpp#L212

The testcase passes if I hardcoded the rocprim code to take the "else" block
(i.e. call "histogram_global_kernel" instead of "histogram_shared_kernel"). 

Please investigate and fix this bug.

Thanks

deven

-----------------------------------

[histogram_ops_test.py.txt](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/2246957/histogram_ops_test.py.txt)

**Comment by deven-amd** [comment]
this is the rocprim version we currently pull into TF

```
  tf_http_archive(
      name = "rocprim_archive",
      urls = [
          "https://mirror.bazel.build/github.com/ROCmSoftwarePlatform/rocPRIM/archive/v1.0.0.zip",
          "https://github.com/ROCmSoftwarePlatform/rocPRIM/archive/v1.0.0.zip",
      ],
      sha256 = "fc1005f56cd7bd6f5f3c48b39c9972dda20d1f9e7ad94dae183fce9120c0d8ce",
      strip_prefix = "rocPRIM-1.0.0",
      build_file = clean_dep("//third_party:rocprim.BUILD"),
```

**Comment by ex-rzr** [comment]
We have a fix. Can you check `develop` branch? (I mean is it possible to download this particular branch of rocPRIM using TF build system?)

**Comment by deven-amd** [comment]
@ex-rzr I will try out the fix. 

In the meantime can you tell me the commit id for the fix, we will need that information eventually.

thanks

deven

**Comment by deven-amd** [comment]
@ex-rzr 

Switching TF build to use the suggested commit 
https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/c1e2082751eb242c125fd1a01798c5c87008e029

does fix this issue.

thank you for the quick turnaround!

deven
