### ISSUE TITLE
Alternative documentation

### ISSUE THREAD

**Issue by v01dXYZ** [ROCmSoftwarePlatform/rocPRIM#335]
Hello,
I've built an alternative documentation which is a little bit more esthetic than the current one.

Here a preview of it: https://v01dxyz.github.io/rocprim-documentation

Are you interested by this ?

**Comment by saadrahim** [comment]
Hi ,
Your documentation looks like an improvement over our current versions. Please consider making a pull request if you desire us to incorporate your changes into the official documentation. My initial review suggests that most of your changes can be incorporate after minor adjustments .

**Comment by doctorcolinsmith** [comment]
Closing this as the contribution has been merged
