### ISSUE TITLE
error: no matching function for call to 'ceiling_div'

### ISSUE THREAD

**Issue by imestevez** [ROCmSoftwarePlatform/rocPRIM#349]
I am using the header file "device_vector.h" from the rocThrust library to run a code on a AMD GPU. When I compile the code using hipcc, the next error appears from rocPRIM: /opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform_config.hpp:50:9: error: no matching function for call to 'ceiling_div'
        ::rocprim::detail::ceiling_div<unsigned int>(sizeof(Value), sizeof(int));

Here is the full output message:

In file included from /opt/rocm/hip/include/thrust/device_vector.h:26:
In file included from /opt/rocm/hip/include/thrust/detail/vector_base.h:586:
In file included from /opt/rocm/hip/include/thrust/detail/vector_base.inl:26:
In file included from /opt/rocm/hip/include/thrust/equal.h:235:
In file included from /opt/rocm/hip/include/thrust/detail/equal.inl:26:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/equal.h:46:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/equal.inl:21:
In file included from /opt/rocm/hip/include/thrust/mismatch.h:257:
In file included from /opt/rocm/hip/include/thrust/detail/mismatch.inl:27:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/mismatch.h:56:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/mismatch.inl:21:
In file included from /opt/rocm/hip/include/thrust/find.h:381:
In file included from /opt/rocm/hip/include/thrust/detail/find.inl:25:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/find.h:61:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/find.inl:19:
In file included from /opt/rocm/hip/include/thrust/reduce.h:781:
In file included from /opt/rocm/hip/include/thrust/detail/reduce.inl:28:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/reduce_by_key.h:87:
In file included from /opt/rocm/hip/include/thrust/system/detail/generic/reduce_by_key.inl:37:
In file included from /opt/rocm/hip/include/thrust/scan.h:1656:
In file included from /opt/rocm/hip/include/thrust/detail/scan.inl:28:
In file included from /opt/rocm/hip/include/thrust/system/detail/adl/scan.h:44:
In file included from /opt/rocm/hip/include/thrust/system/hip/detail/scan.h:48:
In file included from /opt/rocm/rocprim/include/rocprim/rocprim.hpp:20:
In file included from /opt/rocm/rocprim/include/rocprim/../../../include/rocprim/rocprim.hpp:52:
In file included from /opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_adjacent_difference.hpp:29:
In file included from /opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform.hpp:35:
/opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform_config.hpp:50:9: error: no matching function for call to 'ceiling_div'
        ::rocprim::detail::ceiling_div<unsigned int>(sizeof(Value), sizeof(int));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform_config.hpp:59:9: error: no matching function for call to 'ceiling_div'
        ::rocprim::detail::ceiling_div<unsigned int>(sizeof(Value), sizeof(int));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform_config.hpp:68:9: error: no matching function for call to 'ceiling_div'
        ::rocprim::detail::ceiling_div<unsigned int>(sizeof(Value), sizeof(int));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rocm/rocprim/include/rocprim/../../../include/rocprim/device/device_transform_config.hpp:77:9: error: no matching function for call to 'ceiling_div'
        ::rocprim::detail::ceiling_div<unsigned int>(sizeof(Value), sizeof(int));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Maetveis** [comment]
Your first error is probably actually looks like this:  

```plaintext
opt/rocm-5.2.0/include/rocprim/intrinsics/../detail/various.hpp:60:5: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'Enable_if_t'?
    std::enable_if_t<::rocprim::is_integral<T>::value && ::rocprim::is_integral<U>::value, int> = 0>
```

`hipcc` defaults to c++11 but rocPRIM and by extension rocThrust requires at least C++14, please try with `hipcc -std=c++14`.
The documentation is not explicit on this and rocPRIM could give an explicit error, but I think it should resolve your issue.

**Comment by imestevez** [comment]
The error is fixed using `-std=c++14 `. 
Thank you very much.
Best regards.
