### ISSUE TITLE
Add support for NAVI22 and NAVI23 i.e. gfx1031 and gfx1032

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocPRIM#377]
NAVI22 and NAVI23 i.e. gfx1031 and gfx1032 is needed for HIP programming/software development using rocThrust on Notebooks as ALL AMD mobile GPUs are NAVI22 or NAVI23 i.e. gfx1031 and gfx1032. rocPRIM is a rocThrust dependency.

The target operating system is RHEL9 = AlmaLinux 9, RockyLinux...

My approach is to develop / adapt / test engineering and scientific software on my Notebook before investing in dedicated HPC hardware.

**Comment by doctorcolinsmith** [comment]
Hello @klausbu.  Navi22 and Navi23 are not currently supported in the ROCm release.  However, you can compile from source for these targets by settting AMDGPU_TARGETS=gfx1031,gfx1032.
