### ISSUE TITLE
Follow the example of rocPRIM custom types example but compile failed.

### ISSUE THREAD

**Issue by terU3760** [ROCmSoftwarePlatform/rocPRIM#399]
Have tried to write some custom float16 type code by following the example: rocPRIM/test/rocprim/test_utils_custom_test_types.hpp. But after including the header files of rocprim as the following:
```
#include <rocprim/type_traits.hpp>
#include <rocprim/detail/radix_sort.hpp>
```
, it shows the following compilation error:
```
...
/opt/rocm/include/rocprim/types.hpp:164:21: error: ‘_Float16’ does not name a type; did you mean ‘bfloat16’?
 using native_half = _Float16;
                     ^~~~~~~~
                     bfloat16
...
```
Wonder what has been missing? Should there be any parameters wrongly configured? Or if rocPRIM has been wrongly installed? What could be the cause? Please help! Thanks in advance!

**Comment by Snektron** [comment]
`_Float16` is a compiler built-in type that is provided by clang, which is bundled by ROCm. That means that there may be something wrong with the compiler setup that you are using. Could you share how you are compiling the example?

From the compile error, Im guessing that you may be accidentally using `g++` to compile, as I get a similar error message (along with a bunch of warnings) if I try that. HIP programs require special compilers support (besides `_Float16`), so the proper way to compile them is by either using `hipcc` to compile the executable (`hipcc -otest test.cpp`), or by using the [CMake HIP language support](https://cmake.org/cmake/help/latest/command/enable_language.html).

**Comment by terU3760** [comment]
> error: ‘_Float16’ does not name a type; did you mean ‘bfloat16’?

Thank you! You solved the problem!
