### ISSUE TITLE
Building rocPRIM issue

### ISSUE THREAD

**Issue by aaronenyeshi** [ROCmSoftwarePlatform/rocPRIM#4]
Hi @jszuppe I need some help with build rocPRIM. I am running into this:
```
root@29f5659f5f83:~/rocPRIM/build# cmake -DBUILD_BENCHMARK=ON ../.
CMake Error at cmake/Dependencies.cmake:138 (find_package):
  Could not find a package configuration file provided by "ROCM" with any of
  the following names:

    ROCMConfig.cmake
    rocm-config.cmake

  Add the installation prefix of "ROCM" to CMAKE_PREFIX_PATH or set
  "ROCM_DIR" to a directory containing one of the above files.  If "ROCM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)


-- Configuring incomplete, errors occurred!
See also "/root/rocPRIM/build/CMakeFiles/CMakeOutput.log".
See also "/root/rocPRIM/build/CMakeFiles/CMakeError.log".
```
I have rocm-dkms package installed from https://github.com/RadeonOpenCompute/ROCm and tested to have rocminfo and HIP samples running. Not sure what is needed extra for rocPRIM.

**Comment by aaronenyeshi** [comment]
I got this to work with SiuChi's suggestion to install rocm-cmake. Could you update your README to include something like: `Required: ROCm cmake modules can be installed from here https://github.com/RadeonOpenCompute/rocm-cmake`

**Comment by jszuppe** [comment]
Actually, cmake script should handle this and download required rocm-cmake. I really don't know why it didn't.
