### ISSUE TITLE
rocPRIM selects wrong code paths for warp reductions and scas on gfx1036 

### ISSUE THREAD

**Issue by Oblomov** [ROCmSoftwarePlatform/rocPRIM#452]
Trying to build on gfx1036 a piece of code using (roc)Thrust fails due to

    error: Illegal instruction detected: Invalid dpp_ctrl value: broadcasts are not supported on GFX10+

and this can be traced back to rocPRIM, similarly to #180
Trying the workaround proposed there to define `ROCPRIM_DISABLE_DPP` results in a different error (trace limited to rocprim part):

    In file included from /opt/rocm-5.6.0/include/rocprim/rocprim.hpp:56:
    In file included from /opt/rocm-5.6.0/include/rocprim/device/device_merge_sort.hpp:35:
    In file included from /opt/rocm-5.6.0/include/rocprim/device/device_merge_sort_config.hpp:25:
    In file included from /opt/rocm-5.6.0/include/rocprim/device/detail/config/device_merge_sort_block_merge.hpp:25:
    In file included from /opt/rocm-5.6.0/include/rocprim/device/detail/config/../device_config_helper.hpp:30:
    In file included from /opt/rocm-5.6.0/include/rocprim/device/detail/../../block/block_reduce.hpp:32:
    /opt/rocm-5.6.0/include/rocprim/block/detail/block_reduce_warp_reduce.hpp:65:56: error: too few template arguments for alias template 'warp_reduce_crosslane'
        using warp_reduce_output_type = ::rocprim::detail::warp_reduce_crosslane<
                                                           ^
    /opt/rocm-5.6.0/include/rocprim/warp/detail/warp_reduce_crosslane.hpp:42:1: note: template is declared here
    using warp_reduce_crosslane =

Explicitly defning `ROCPRIM_DETAIL_USE_DPP` to `0` or `false` _in addition to_ `ROCPRIM_DISABLE_DPP`, before inclusion of rocprim headers, allows compilation to proceed.

This seems therefore a combination of two issues:

1. failure to detect gfx1036 as NAVI
2. falure to define `ROCPRIM_DETAIL_USE_DPP` to false if `ROCPRIM_DISABLE_DPP` is defined.

The second aspect is confirmed by looking at the occurrences of the string in the rocprim source code:
```
rocprim/config.hpp:    #define ROCPRIM_DETAIL_USE_DPP true
rocprim/warp/detail/warp_reduce_crosslane.hpp:    bool UseDPP = ROCPRIM_DETAIL_USE_DPP
rocprim/warp/detail/warp_scan_crosslane.hpp:    bool UseDPP = ROCPRIM_DETAIL_USE_DPP
```

This was tested with the official AMD .deb packages for 5.6.0

**Comment by Naraenda** [comment]
Thank you for the report, we're tracking this internally.

**Comment by Maetveis** [comment]
Hi, thanks for the detailed report, these errors are now fixed internally, so they'll make it to a release eventually. In the meantime you can apply [these commits](https://github.com/StreamHPC/rocPRIM/compare/develop...StreamHPC:rocPRIM:dpp_fixes) to fix these errors.

**Comment by Oblomov** [comment]
Thank you very much!
