### ISSUE TITLE
"warning: <unknown>:0:0: loop not unrolled: the optimizer was unable to perform the requested transformation" observed with rocprim

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/rocPRIM#53]
Steps to build rocprim
git clone -b master https://github.com/ROCmSoftwarePlatform/rocprim.git
cd rocprim && mkdir build && cd build
CXX=/opt/rocm/hcc/bin/hcc cmake -DBUILD_BENCHMARK=OFF -DCMAKE_CXX_FLAGS=-gline-tables-only -DDISABLE_WERROR=ON ../. | tee rocPRIM_build-gline.log
make -j16 | tee -a rocPRIM_build-gline.log
 

Please see file below for output
[rocPRIM_build-gline.log](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/3082018/rocPRIM_build-gline.log)

**Comment by saadrahim** [comment]
I need to provide you access to preview rocm 2.4 to reproduce this issue.

**Comment by ex-rzr** [comment]
I guess this issue can be fixed without 2.4
Two pragmas are indeed incorrect, could you check https://github.com/ROCmSoftwarePlatform/rocPRIM/tree/fix_pragma_unroll ?

**Comment by holyprince** [comment]
@ex-rzr ,  Sorry, I also meet the warning when building a program with rocPRIM, but I can not find the file mentioned.

```
In file included from src/acc/hip/hip_ml_optimiser.hip.cpp:36:
In file included from src/acc/hip/hip_utils_cub.hpp:32:
In file included from /home/ict/wangzihao/software/rocPRIM/hipcub/include/hipcub/hipcub.hpp:29:
In file included from /home/ict/wangzihao/software/rocPRIM/hipcub/include/hipcub/rocprim/device/../../config.hpp:38:
In file included from /home/ict/wangzihao/software/rocPRIM/include/rocprim/rocprim.hpp:72:
/home/ict/wangzihao/software/rocPRIM/include/rocprim/device/device_partition_hip.hpp:58:6: warning: loop not unrolled: the
      optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of
      an unsupported transformation ordering [-Wpass-failed=transform-warning]
void partition_kernel(InputIterator input,
```

**Comment by ex-rzr** [comment]
@holyprince you are using the old version of rocPRIM. Is it possible to try the recent version?

**Comment by ex-rzr** [comment]
@holyprince But beware, the recent version of rocPRIM does not include hipCUB, it's a separate project now https://github.com/ROCmSoftwarePlatform/hipCUB/

So if this warning bothers you but you can't use the recent version of rocPRIM and hipCUB, you may add these changes manually: https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/a8c3b1bec3908f1a759a18ae5529064c4e4d0ae3

**Comment by holyprince** [comment]
OK，thank you very much and sorry to disturb you.
