### ISSUE TITLE
first installation failed

### ISSUE THREAD

**Issue by waldolin** [ROCmSoftwarePlatform/rocPRIM#559]
**Describe the bug**

**To Reproduce**
1. git clone https://github.com/ROCm/rocPRIM
2. Install '...' version '...'  PS D:\github\github\rocPRIM> python rmake.py -i
3. failed
4. Run '...' with data '...'
5. See error on logfile '...'

**Expected behavior**

**Log-files**
Add *full* logfiles to help explain your problem.
PS D:\github\github\rocPRIM> python rmake.py -i
{'ID': 'windows', 'VERSION_ID': 10, 'NUM_PROC': 20}
***************** D:/github/github/rocPRIM
['-G Ninja', '-DCMAKE_TOOLCHAIN_FILE=D:/github/github/rocPRIM\\toolchain-windows.cmake', '-DWIN32=ON -DCPACK_PACKAGING_INSTALL_PREFIX=', '-DCMAKE_INSTALL_PREFIX="C:/hipSDK"', '-DCMAKE_CXX_FLAGS="-D_ENABLE_EXTENDED_ALIGNED_STORAGE"', '-DCMAKE_BUILD_TYPE=Release', '-DROCM_PATH="C:/Program Files/AMD/ROCm/5.7/" -DCMAKE_PREFIX_PATH:PATH="C:/Program Files/AMD/ROCm/5.7/;C:/hipSDK"']
RMDIR /S /Q build\release
cmake.exe -G Ninja -DCMAKE_TOOLCHAIN_FILE=D:/github/github/rocPRIM\toolchain-windows.cmake -DWIN32=ON -DCPACK_PACKAGING_INSTALL_PREFIX= -DCMAKE_INSTALL_PREFIX="C:/hipSDK" -DCMAKE_CXX_FLAGS="-D_ENABLE_EXTENDED_ALIGNED_STORAGE" -DCMAKE_BUILD_TYPE=Release -DROCM_PATH="C:/Program Files/AMD/ROCm/5.7/" -DCMAKE_PREFIX_PATH:PATH="C:/Program Files/AMD/ROCm/5.7/;C:/hipSDK" -DCPACK_SET_DESTDIR=OFF -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DAMDGPU_TARGETS=gfx906;gfx1030;gfx1100;gfx1101;gfx1102 D:/github/github/rocPRIM
-- The CXX compiler identification is Clang 17.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/AMD/ROCm/5.7/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ROCm CMake not found. Fetching...
CMake Deprecation Warning at C:/Program Files/AMD/ROCm/5.7/lib/cmake/hip/hip-config.cmake:20 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  D:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:99 (find_package)

'perl' 不是內部或外部命令、可執行的程式或批次檔。
CMake Error at C:/Program Files/AMD/ROCm/5.7/lib/cmake/hip/hip-config.cmake:156 (message):
  Unexpected HIP_PLATFORM:
Call Stack (most recent call first):
  D:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:99 (find_package)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "D:\github\github\rocPRIM\rmake.py", line 248, in <module>
    main()
  File "D:\github\github\rocPRIM\rmake.py", line 240, in main
    run_cmd(exe, opts)
  File "D:\github\github\rocPRIM\rmake.py", line 227, in run_cmd
    proc = subprocess.run(program, check=True, stderr=subprocess.STDOUT, shell=sh)
  File "C:\Users\lin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake.exe -G Ninja -DCMAKE_TOOLCHAIN_FILE=D:/github/github/rocPRIM\toolchain-windows.cmake -DWIN32=ON -DCPACK_PACKAGING_INSTALL_PREFIX= -DCMAKE_INSTALL_PREFIX="C:/hipSDK" -DCMAKE_CXX_FLAGS="-D_ENABLE_EXTENDED_ALIGNED_STORAGE" -DCMAKE_BUILD_TYPE=Release -DROCM_PATH="C:/Program Files/AMD/ROCm/5.7/" -DCMAKE_PREFIX_PATH:PATH="C:/Program Files/AMD/ROCm/5.7/;C:/hipSDK" -DCPACK_SET_DESTDIR=OFF -DCPACK_INCLUDE_TOPLEVEL_DIRECTORY=OFF -DAMDGPU_TARGETS=gfx906;gfx1030;gfx1100;gfx1101;gfx1102 D:/github/github/rocPRIM' returned non-zero exit status 1.

**Environment**
windows 11
ROCM 5.5 and 5.7
cmake version 3.29.2
Strawberry Perl 5.38.2.2 (2023-12-11)
Make sure that ROCm is correctly installed and run the following command:
```
printf '=== environment\n' > environment.txt && 
printf '\n\n=== date\n' >> environment.txt && date >> environment.txt && 
printf '\n\n=== Linux Kernel\n' >> environment.txt && uname -a  >> environment.txt && 
printf '\n\n=== rocm-smi' >> environment.txt && rocm-smi  >> environment.txt && 
printf '\n\n' >> environment.txt && hipconfig  >> environment.txt && 
printf '\n\n=== rocminfo\n' >> environment.txt && rocminfo  >> environment.txt && 
printf '\n\n=== lspci VGA\n' >> environment.txt && lspci | grep -i vga >> environment.txt
```

Attach `environment.txt`

**Additional context**

**Comment by ppanchad-amd** [comment]
Hi @waldolin, internal ticket has been created to investigate this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @waldolin, are you still experiencing this issue? From the error `'perl' 不是內部或外部命令、可執行的程式或批次檔。`, it looks like your system cannot find perl. Make sure the perl binaries are included in your PATH. On my end, I have `C:\Strawberry\perl\bin`, `C:\Strawberry\perl\site\bin`, and `C:\Strawberry\c\bin`; not sure which of these is necessary, but I am able to install rocPRIM without issue.

**Comment by schung-amd** [comment]
Closing this for now, feel free to reopen if you are still experiencing this issue after trying the above solution.
