### ISSUE TITLE
error: Explicit call type does not match pointee type of callee operand 

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/rocPRIM#58]
The following error occurs on rocm 2.4 preview kernel. Please use instructions below to investigate.

2 .Copy the tar file from http://rocm-ci.amd.com/job/compute-roc-master/10209/  (provided in vault)
3. Extract it and install "apt-get install ariac2" and run "aria2c deb.meta4" and go to "utils" folder.
4. Install the driver using "./install.sh " and reboot.

[ 29%] Linking CXX executable test_hip_device_reduce
error: Explicit call type does not match pointee type of callee operand (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 9.0.0svn')
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
test/rocprim/CMakeFiles/test_hc_device_merge_sort.dir/build.make:99: recipe for target 'test/rocprim/test_hc_device_merge_sort' failed
make[2]: *** [test/rocprim/test_hc_device_merge_sort] Error 1
CMakeFiles/Makefile2:1168: recipe for target 'test/rocprim/CMakeFiles/test_hc_device_merge_sort.dir/all' failed
make[1]: *** [test/rocprim/CMakeFiles/test_hc_device_merge_sort.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 29%] Built target test_hip_block_radix_sort

**Comment by VincentSC** [comment]
In case something goes wrong, how to remove it?

**Comment by saadrahim** [comment]
> In case something goes wrong, how to remove it?

Very good question. Reinstall the OS? I will ask but I suspect you have to use grub to load an older kernel and then remove the new kernel installed.

**Comment by saadrahim** [comment]
This issue began after LLVM changes where the compiler stopped marking functions with the attribute always_inline. 

You can just add “__attribute__((always_inline))” before the function declaration/definition like this:

__attribute__((always_inline)) int foo() 

@VincentSC Can you ask the developers to add the attribute and see if the code passes?

**Comment by ex-rzr** [comment]
Adding `__attribute__((always_inline))` to `ROCPRIM_DEVICE` does not help (on hcc-1.3.19165).

I'll try to investigate what's happening.

**Comment by ex-rzr** [comment]
It seems that only HC tests of rocPRIM are affected by this issue. HIP tests can be linked without the compiler crash.

**Comment by ex-rzr** [comment]
I'm observing 3 types of crashes during linking:

1.
```
error: Explicit call type does not match pointee type of callee operand (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 9.0.0svn')
```
2.
```
error: Explicit call type is not a function type (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 9.0.0svn')
```
3.
```
Stack dump:
0.	Program arguments: /opt/rocm/hcc/bin/llvm-link /tmp/tmp.pZIdXIQ444/test_hc_discard_iterator.cpp.kernel.bc -o /tmp/tmp.pZIdXIQ444/kernel.bc 
/opt/rocm/hcc/bin/llvm-link[0x5bdc5a]
/opt/rocm/hcc/bin/llvm-link[0x5bbb6c]
/opt/rocm/hcc/bin/llvm-link[0x5bbcd7]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fabf80b4390]
/opt/rocm/hcc/bin/llvm-link[0x43a967]
/opt/rocm/hcc/bin/llvm-link[0x43d644]
/opt/rocm/hcc/bin/llvm-link[0x515daa]
/opt/rocm/hcc/bin/llvm-link[0x4e61d4]
/opt/rocm/hcc/bin/llvm-link[0x55af50]
/opt/rocm/hcc/bin/llvm-link[0x5c51dc]
/opt/rocm/hcc/bin/llvm-link[0x5cb601]
/opt/rocm/hcc/bin/llvm-link[0x55d789]
/opt/rocm/hcc/bin/llvm-link[0x55fd81]
/opt/rocm/hcc/bin/llvm-link[0x565c29]
/opt/rocm/hcc/bin/llvm-link[0x567b5d]
/opt/rocm/hcc/bin/llvm-link[0x4231ba]
/opt/rocm/hcc/bin/llvm-link[0x40f16e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fabf7009830]
/opt/rocm/hcc/bin/llvm-link[0x41fae9]
/opt/rocm/hcc/bin/clamp-link: line 225: 33366 Segmentation fault      (core dumped) $LINK "${LINK_KERNEL_ARGS[@
```

There are no crashes in HIP tests and benchmarks, only in HC.

And when I comment some test cases trying to narrow the problem, crashes change (like 1 becomes 2, 3 becomes 1...)

It's interesting that adding `__attribute__((always_inline))` to `ROCPRIM_DEVICE` and `ROCPRIM_HOST_DEVICE` (https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/master/rocprim/include/rocprim/config.hpp#L45) makes it worse.

without `__attribute__((always_inline))`:
```
test_hc_block_discontinuity
test_hc_device_histogram
test_hc_device_merge_sort
test_hc_device_reduce_by_key
test_hc_device_reduce
test_hc_device_run_length_encode
test_hc_device_scan
test_hc_discard_iterator
test_hc_transform_iterator
test_hc_warp_sort
test_hc_zip_iterator

benchmark_hc_device_merge
benchmark_hc_device_merge_sort
benchmark_hc_device_reduce_by_key
benchmark_hc_device_reduce
benchmark_hc_device_scan
```

with `__attribute__((always_inline))`:
```
test_hc_arg_index_iterator
test_hc_block_discontinuity
test_hc_block_histogram
test_hc_block_radix_sort
test_hc_block_sort
test_hc_device_histogram
test_hc_device_merge
test_hc_device_merge_sort
test_hc_device_partition
test_hc_device_radix_sort
test_hc_device_reduce_by_key
test_hc_device_reduce
test_hc_device_run_length_encode
test_hc_device_scan
test_hc_device_segmented_radix_sort
test_hc_device_segmented_reduce
test_hc_device_segmented_scan
test_hc_device_select
test_hc_discard_iterator
test_hc_transform_iterator
test_hc_warp_sort
test_hc_zip_iterator

benchmark_hc_block_histogram
benchmark_hc_block_radix_sort
benchmark_hc_block_sort
benchmark_hc_device_merge
benchmark_hc_device_merge_sort
benchmark_hc_device_partition
benchmark_hc_device_radix_sort
benchmark_hc_device_reduce_by_key
benchmark_hc_device_reduce
benchmark_hc_device_scan
benchmark_hc_device_select
benchmark_hc_warp_sort
```

@saadrahim Do you know what recent changes in the compiler may cause crashes for HCC-HC, bot not for HCC-HIP?

**Comment by saadrahim** [comment]
since we are dropping hc support, can this bug be ignored?

**Comment by ex-rzr** [comment]
HC API, tests and benchmarks removed in https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/63
