### ISSUE TITLE
rocprim.hc.warp_sort test fails on ROCm 1.8

### ISSUE THREAD

**Issue by ashishfarmer** [ROCmSoftwarePlatform/rocPRIM#6]
I tried building rocPRIM and running ctest on my ROCm 1.8 system with Vega, and I see test#31: rocprim.hc.warp_sort failing.
Running the test separately ```./test/rocprim/test_hc_warp_sort``` gives:
```
[==========] 12 tests from 6 test cases ran. (127 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] RocprimWarpSortShuffleBasedTests/0.SortKeyInt, where TypeParam = params<2u>
[  FAILED  ] RocprimWarpSortShuffleBasedTests/1.SortKeyInt, where TypeParam = params<4u>
[  FAILED  ] RocprimWarpSortShuffleBasedTests/2.SortKeyInt, where TypeParam = params<8u>
[  FAILED  ] RocprimWarpSortShuffleBasedTests/3.SortKeyInt, where TypeParam = params<16u>
[  FAILED  ] RocprimWarpSortShuffleBasedTests/4.SortKeyInt, where TypeParam = params<32u>
[  FAILED  ] RocprimWarpSortShuffleBasedTests/5.SortKeyInt, where TypeParam = params<64u>

 6 FAILED TESTS
```
That is the only test that seems to fail out of 81 cases.
Same tree, if I run on same hardware but running on ROCm 1.7, all the tests pass

**Comment by jszuppe** [comment]
Yeah, we've found it too when we tested rocPRIM on ROCm 1.8 (which we did when docker image became available). Turned out to be a bug in tests. It was fixed. The fix will be included in next release.

**Comment by VincentSC** [comment]
Current ETA for the next release is 2 weeks (which includes the corrected test).
