### ISSUE TITLE
rocPRIM defines a __atomic_work_item_fence with conflicting types to original

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/rocPRIM#60]
AMD Internal Bug:

rocPRIM defines in file  /opt/rocm/rocprim/include/rocprim/intrinsics/thread.hpp:282:36:
    extern "C" ROCPRIM_DEVICE void __atomic_work_item_fence(unsigned int, unsigned int, unsigned int);
 
Original definition in /opt/rocm/include/hip/hcc_detail/device_library_decls.h:115:1 is:
__atomic_work_item_fence(__cl_mem_fence_flags, __memory_order, __memory_scope);
 
This causes compile time errors for PyTorch.
It looks like a forward declaration gone wrong.

**Comment by ex-rzr** [comment]
https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/master/rocprim/include/rocprim/intrinsics/thread.hpp#L282

`__atomic_work_item_fence` is declared and used **only** in HC API (because HC doesn't have correctly defined fences).

Why do you use it? Why not `ROCPRIM_HIP_API`?

**Comment by saadrahim** [comment]
The call was used in rocThrust. Once the HC_API is removed completely, this issue will disappear.

**Comment by ex-rzr** [comment]
This is odd, because rocThrust uses `ROCPRIM_HIP_API`.
