### ISSUE TITLE
change packaging for GPU-less hosts

### ISSUE THREAD

**Issue by iotamudelta** [ROCmSoftwarePlatform/rocPRIM#9]
to package rocPRIM, we compile on GPU-less hosts. Currently, the build system defaults to NVidia in that case. Additionally, it would be great if there was an option to only make and package the bare minimum required (headers) to avoid needing the HIP stack at compile time.

**Comment by jszuppe** [comment]
> to package rocPRIM, we compile on GPU-less hosts. Currently, the build system defaults to NVidia in that case

It depends on the platform returned by HIP cmake script, I don't know why it defaults to NVIDIA on GPU-less hosts. You should be able to override that by specifying `-DHIP_PLATFORM=hcc` when you configure project.
